version: '3.5'

services:
  app:
    build: .
    command: bash Deployment/bashes/RunBash.sh
    container_name: delta_project
    volumes:
      - ./src:/src
      - "./db/files/static:/src/static:ro"
      - "./db/files/media:/src/media:rw"
    ports:
      - "8000:8000"
    depends_on: 
          db:
            condition: service_healthy

  db:
     image: postgres:10-alpine
     restart: always
     environment: 
       POSTGRES_USER: parsa
       POSTGRES_NAME: delta
       POSTGRES_PASSWORD: parsa1234
       POSTGRES_PORT: 5432
     volumes:
       - ./data/postgres-data:/var/lib/postgresql/data
     healthcheck:
          test: "exit 0"
  
  pgadmin:
     image: dpage/pgadmin4:latest
     container_name: delta-pgadmin
     depends_on:
       - db
     ports:
       - "5051:80"
     environment:
       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
       PGADMIN_DEFAULT_PASSWORD: parsa1234
     restart: always



