version: '3'

services:
  app:
    build: .
    command: bash Deployment/bashes/RunBash.sh
    container_name: delta_project
    volumes:
      - ./src:/src
      - "./db/files/static:/src/static:ro"
      - "./db/files/media:/src/media:rw"
    ports:
      - "8000:8000"
    links: 
      - db

  db:
     image: postgres:10-alpine
     restart: always
     environment: 
       POSTGRES_USER: parsa
       POSTGRES_NAME: delta
       POSTGRES_PASSWORD: parsa1234
     volumes:
       - ./data/postgres-data:/var/lib/postgresql/data
      

