# Generated by Django 3.2 on 2023-02-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_tenant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_tenant_type',
        ),
    ]
