# Generated by Django 3.2 on 2023-02-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0006_alter_customuser_user_tenant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_tenant_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
