# Generated by Django 3.2 on 2023-02-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230206_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tenant_id',
            new_name='user_tenant',
        ),
    ]
