# Generated by Django 3.2 on 2023-02-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_user_name', models.CharField(max_length=200)),
                ('tenant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_shared.tenanttype')),
            ],
        ),
    ]
