# Generated by Django 3.2 on 2023-02-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_tenant', '0002_alter_tenantuser_tenant_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant_user_name',
        ),
    ]
