# Generated by Django 3.2 on 2023-02-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_tenant', '0003_remove_tenantuser_tenant_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
