# Generated by Django 3.2 on 2023-02-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_tenant', '0007_tenantuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
